version: '3'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - sales-web
      - sales-web1
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8070:8070
  javamelody:
    image: javamelody
    environment:
      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core
    ports:
      - 1337:1337

  postgres:
    image: library/postgres:12.6
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=javamelodydb
    ports:
    - 5433:5432

#  sales-core:
#    image: cuba-sample-sales-core
#    environment:
#      - CUBA_DATASOURCE_HOST=postgres
#      - CUBA_DATASOURCE_PORT=5432
#      - CUBA_DATASOURCE_PASSWORD=1234
#      - CUBA_DATASOURCE_USER=postgres
#      - CUBA_DATASOURCE_DBNAME=javamelodydb
#      - CUBA_CLUSTER_ENABLED=true
#      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
#      - CUBA_WEBHOSTNAME=sales-core
#      - CUBA_WEBPORT=8079
#      - CUBA_WEBCONTEXTNAME=app-core
##    command: java -Dapp.home=/usr/src/cuba-app1/home -jar /usr/src/cuba-app1/app-core.jar
##      - CUBA.CLUSTER.JGROUPSCONFIG=/my_jgroups_tcp.xml
#  sales-web:
#    image: cuba-sample-sales-web
#    environment:
#      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core
#      - CUBA_USELOCALSERVICEINVOCATION=false
#      - CUBA_WEBHOSTNAME=sales-web
#
#  sales-core1:
#    image: cuba-sample-sales-core
#    environment:
#      - CUBA_DATASOURCE_HOST=postgres #postgres
#      - CUBA_DATASOURCE_PORT=5432
#      - CUBA_DATASOURCE_PASSWORD=1234
#      - CUBA_DATASOURCE_USER=postgres
#      - CUBA_DATASOURCE_DBNAME=javamelodydb
#      - CUBA_CLUSTER_ENABLED=true
#      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
#      - CUBA_WEBHOSTNAME=sales-core1
#      - CUBA_WEBPORT=8079
#      - CUBA_WEBCONTEXTNAME=app-core
##      - CUBA.CLUSTER.JGROUPSCONFIG=/my_jgroups_tcp.xml
#  sales-web1:
#    image: cuba-sample-sales-web
#    environment:
#      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core, http://sales-core1:8079/app-core
#      - CUBA_USELOCALSERVICEINVOCATION=false

  sales-core:
    image: cuba-sample-sales-core
    environment:
      - CUBA_DATASOURCE_HOST=postgres
      - CUBA_DATASOURCE_PORT=5432
      - CUBA_DATASOURCE_PASSWORD=1234
      - CUBA_DATASOURCE_USER=postgres
      - CUBA_DATASOURCE_DBNAME=javamelodydb
      - CUBA_CLUSTER_ENABLED=true
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
      - CUBA_WEBHOSTNAME=sales-core
      - CUBA_WEBPORT=8079
      - CUBA_WEBCONTEXTNAME=app-core
#      - CUBA.CLUSTER.JGROUPSCONFIG=/my_jgroups_tcp.xml
#    ports:
#      - 8079:8079
  sales-web:
    image: cuba-sample-sales-web
    environment:
      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core
      - CUBA_USELOCALSERVICEINVOCATION=false
      - CUBA_WEBHOSTNAME=sales-web

  sales-core1:
    image: cuba-sample-sales-core
    environment:
      - CUBA_DATASOURCE_HOST=postgres #postgres
      - CUBA_DATASOURCE_PORT=5432
      - CUBA_DATASOURCE_PASSWORD=1234
      - CUBA_DATASOURCE_USER=postgres
      - CUBA_DATASOURCE_DBNAME=javamelodydb
      - CUBA_CLUSTER_ENABLED=false
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
      - CUBA_WEBHOSTNAME=sales-core1
      - CUBA_WEBPORT=8079
      - CUBA_WEBCONTEXTNAME=app-core
      - CUBA.CLUSTER.JGROUPSCONFIG=/jgroups_tcp.xml
  sales-web1:
    image: cuba-sample-sales-web
    environment:
      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core, http://sales-core1:8079/app-core
      - CUBA_USELOCALSERVICEINVOCATION=false

